FROM jupyter/datascience-notebook

RUN conda install -y conda-forge::r-languageserver
RUN conda install -y conda-forge::r-pacman
RUN conda install -y conda-forge::r-stringr
RUN conda install -y conda-forge::r-data.table
RUN conda install -y conda-forge::r-sparql
RUN conda install -y conda-forge::r-vtree


RUN echo "Hello World!"

RUN echo "I am building up your code environment now..."
