FROM jupyter/datascience-notebook

RUN conda install -y conda-forge::r-languageserver r-pacman r-stringr r-data.table r-sparql r-vtree

RUN echo "Hello World!"

RUN echo "I am building up your code environment now..."
